version: '3.8'

services:
  postgres:
    image: postgres
    container_name: MedicalCLinicDB
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
